### ISSUE TITLE
'Post Scriptum' has been changed to PS

### ISSUE THREAD

**Issue by 0xJoeMama** [LlamaramaTeam/LlamaramaTeam.github.io#1]
There is a reason behind everything I do. Please revert that change.

Thanks for your attention,
your dearest, Joe.

**Comment by 0xJoeMama** [comment]
How dare you!

**Comment by 0xJoeMama** [comment]
Also, I would like to thank you for fixing this issue! Keep up the great work! Signed by JoeMama.

**Comment by Accieo** [comment]
Hahah 😜
